export const districtsFlorianopolis = [
  "Abraão",
  "Agronômica",
  "Área Rural de Florianópolis",
  "Armação do Pântano do Sul",
  "Balneário",
  "Barra da Lagoa",
  "Bom Abrigo",
  "Cachoeira do Bom Jesus",
  "Cacupé",
  "Campeche",
  "Canasvieiras",
  "Canto",
  "Capoeiras",
  "Carianos",
  "Carvoeira",
  "Centro",
  "Coloninha",
  "Coqueiros",
  "Córrego Grande",
  "Costeira do Pirajubaé",
  "Daniela",
  "Estreito",
  "Ingleses do Rio Vermelho",
  "Itacorubi",
  "Itaguaçu",
  "Jardim Atlântico",
  "João Paulo",
  "José Mendes",
  "Jurerê",
  "Jurerê Internacional",
  "Lagoa da Conceição",
  "Monte Cristo",
  "Monte Verde",
  "Morro das Pedras",
  "Pantanal",
  "Pântano do Sul",
  "Ponta das Canas",
  "Praia Brava",
  "Ratones",
  "Ribeirão da Ilha",
  "Rio Tavares",
  "Saco dos Limões",
  "Saco Grande",
  "Sambaqui",
  "Santa Mônica",
  "Santo Antônio de Lisboa",
  "São João do Rio Vermelho",
  "Tapera",
  "Tapera da Base",
  "Trindade",
  "Vargem do Bom Jesus",
  "Vargem Grande",
  "Vargem Pequena"
]
